[package]
name = "opencade_client"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = { version = "0.32.1", features = ["persistence"] }
egui   = "0.32.1"
serde  = { version = "1.0", features = ["derive"] }
